FROM python:3.11

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    curl \
    wget \
    git \
    bash \
    vim \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli" -o /usr/local/bin/ani-cli \
    && chmod +x /usr/local/bin/ani-cli

WORKDIR /workspace
